[package]
name = "sm-crypto"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4.3"
num-bigint = { version = "0.4.6", features = ["rand"] }
num-traits = "0.2.19"
rand = { version = "0.8.5", features = ["std"] }
